[[redirects]]
  from = "/commcan-rehoboth/*"
  to = "https://widgets.dispenseapp.com/:splat"
  status = 200
  force = false
  headers = {dispense-store-id = "075f447fd7e35cd9", dispense-menu-path = "/commcan-rehoboth", x-forwarded-host = "yourgreenpackage.com" }
[[redirects]]
  from = "/MissionBrookline/*"
  to = "https://widgets.dispenseapp.com/:splat"
  status = 200
  force = false
  headers = {dispense-store-id = "65bc90665cab3eb8", dispense-menu-path = "/MissionBrookline", x-forwarded-host = "yourgreenpackage.com" }
[[redirects]]
  from = "/InsaSalem/*"
  to = "https://widgets.dispenseapp.com/:splat"
  status = 200
  force = false
  headers = {dispense-store-id = "4344b903ec92c253", dispense-menu-path = "/InsaSalem", x-forwarded-host = "yourgreenpackage.com" }