[[redirects]]
  from = "/commcann-rehoboth/*"
  to = "https://widgets.dispenseapp.com"
  status = 200
  force = false
  headers = {dispense-store-id = "075f447fd7e35cd9", dispense-menu-path = "/commcann-rehoboth", x-forwarded-host = "yourgreenpackage.com" }